name: CI
on: pull_request

jobs:
  build_linux:
    name: Build Linux binary
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.9.0"
      POETRY_VERSION: "1.1.11"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: Build binary
        run: poetry run pyinstaller cook-import.spec


  build_macos:
    if: ${{ false }}
    name: Build macOS binary
    runs-on: macos-11
    env:
      # SIGNING_AUTH: ${{ secrets.SIGNING_AUTH }}
      # NOTARIZATION_USER: ${{ secrets.NOTARIZATION_USER }}
      # NOTARIZATION_PASS: ${{ secrets.NOTARIZATION_PASS }}
      # AUTOMATION_GITHUB_TOKEN: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
      # # We need the official Python, because the GA ones only support newer macOS versions
      # # The deployment target is picked up by the Python build tools automatically
      # # If updated, make sure to also set LSMinimumSystemVersion in SABnzbd.spec
      PYTHON_VERSION: "3.10.0"
      POETRY_VERSION: "1.1.11"
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      # We need to force compile for universal2 support
      CFLAGS: -arch arm64 -arch x86_64

    steps:
      - uses: actions/checkout@v2
      - name: Cache Python download
        id: cache-python-download
        uses: actions/cache@v2
        with:
          path: ~/python.pkg
          key: macOS-Python-${{ env.PYTHON_VERSION }}
      - name: Get Python
        if: steps.cache-python-download.outputs.cache-hit != 'true'
        run: curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macos11.pkg -o ~/python.pkg
      - name: Install Python
        run: sudo installer -pkg ~/python.pkg -target /
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: Build binary
        run: poetry run pyinstaller cook-import.spec
